import streamlit as st
from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
)

from src.pdf_parser import extract_text_from_pdf

from src.matcher import (
    calculate_similarity,
    calculate_final_score
)

from src.skill_extractor import (
    extract_skills,
    normalize_skills,
    extract_skill_evidence
)

from src.recommendations import (
    generate_recommendations,
    calculate_experience_match
)


# ============================================================
# PDF REPORT GENERATOR
# ============================================================

def create_pdf_report(
    final_score,
    semantic_score,
    skill_percentage,
    experience_match,
    matched_skills,
    missing_skills,
    recommendations,
    evidence,
    ats_result=None,
):
    """Create a professional PDF analysis report in memory."""
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="Resume Job Match Analysis Report",
        author="Resume Job Match Analyzer",
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=22,
        leading=27,
        alignment=TA_CENTER,
        spaceAfter=8,
    )

    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        alignment=TA_CENTER,
        textColor=colors.grey,
        spaceAfter=18,
    )

    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading2"],
        fontSize=15,
        leading=19,
        spaceBefore=12,
        spaceAfter=8,
    )

    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["BodyText"],
        fontSize=10,
        leading=14,
        spaceAfter=5,
    )

    small_style = ParagraphStyle(
        "ReportSmall",
        parent=styles["BodyText"],
        fontSize=8.5,
        leading=12,
        textColor=colors.grey,
    )

    story = []

    story.append(Paragraph("Resume → Job Match Analysis", title_style))
    story.append(
        Paragraph(
            "Generated by Resume → Job Match Analyzer",
            subtitle_style,
        )
    )

    # Score table
    score_data = [
        ["Final Match Score", "Semantic Similarity", "Skill Coverage"],
        [
            f"{float(final_score):.2f}%",
            f"{float(semantic_score):.2f}%",
            f"{float(skill_percentage):.1f}%",
        ],
    ]

    score_table = Table(
        score_data,
        colWidths=[55 * mm, 55 * mm, 55 * mm],
    )
    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EAF2FF")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#17365D")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("TOPPADDING", (0, 0), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
            ]
        )
    )
    story.append(score_table)
    story.append(Spacer(1, 8))

    story.append(Paragraph("Experience Match", heading_style))
    story.append(Paragraph(escape(str(experience_match)), body_style))

    story.append(Paragraph("Matched Skills", heading_style))
    if matched_skills:
        for skill in matched_skills:
            story.append(Paragraph(f"✓ {escape(str(skill))}", body_style))
    else:
        story.append(Paragraph("No matching skills detected.", body_style))

    story.append(Paragraph("Missing Skills", heading_style))
    if missing_skills:
        for skill in missing_skills:
            story.append(Paragraph(f"✗ {escape(str(skill))}", body_style))
    else:
        story.append(Paragraph("No major missing skills detected.", body_style))

    story.append(Paragraph("Skill Evidence", heading_style))
    if evidence:
        for skill in matched_skills:
            text = evidence.get(skill)
            if text:
                story.append(
                    KeepTogether(
                        [
                            Paragraph(
                                f"<b>{escape(str(skill))}</b>",
                                body_style,
                            ),
                            Paragraph(
                                f"Resume evidence: {escape(str(text))}",
                                small_style,
                            ),
                            Spacer(1, 4),
                        ]
                    )
                )
    else:
        story.append(Paragraph("No evidence available.", body_style))

    story.append(Paragraph("Suggested Improvements", heading_style))
    if recommendations:
        for index, recommendation in enumerate(recommendations, start=1):
            story.append(
                Paragraph(
                    f"<b>{index}.</b> {escape(str(recommendation))}",
                    body_style,
                )
            )
    else:
        story.append(
            Paragraph(
                "Your resume already covers the major requirements of this job.",
                body_style,
            )
        )

    if ats_result:
        story.append(Paragraph("ATS Compatibility", heading_style))
        story.append(Paragraph(
            f"ATS heuristic score: {float(ats_result['score']):.1f}% ({escape(str(ats_result['status']))})",
            body_style,
        ))
        story.append(Paragraph(
            f"Job-specific keyword coverage: {float(ats_result['keyword_coverage']):.1f}%",
            body_style,
        ))
        if ats_result.get("missing_keywords"):
            story.append(Paragraph(
                "Missing ATS keywords: " + escape(", ".join(ats_result["missing_keywords"])),
                body_style,
            ))
        if ats_result.get("improvements"):
            story.append(Paragraph("ATS Improvements", body_style))
            for index, item in enumerate(ats_result["improvements"], start=1):
                story.append(Paragraph(
                    f"<b>{index}.</b> {escape(str(item))}",
                    body_style,
                ))

    story.append(Paragraph("Score Breakdown", heading_style))
    breakdown_data = [
        ["Component", "Score", "Weight"],
        ["Semantic Similarity", f"{float(semantic_score):.2f}%", "60%"],
        ["Skill Coverage", f"{float(skill_percentage):.1f}%", "30%"],
        [
            "Experience",
            f"{100 if experience_match == 'Good' else 60 if experience_match == 'Moderate' else 30}%",
            "10%",
        ],
    ]

    breakdown_table = Table(
        breakdown_data,
        colWidths=[75 * mm, 45 * mm, 45 * mm],
    )
    breakdown_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F2F2F2")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.append(breakdown_table)
    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            "Built with Python · Sentence Transformers · Scikit-learn · PyMuPDF · Streamlit",
            small_style,
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()


# ============================================================
# ATS ANALYZER
# ============================================================

def analyze_ats(resume_text, job_description, jd_skills):
    """Heuristic ATS analysis for resume structure and job-specific keywords."""
    import re

    text = resume_text or ""
    lower_text = text.lower()

    section_aliases = {
        "Contact Information": ["email", "phone", "linkedin", "github"],
        "Summary / Objective": ["summary", "objective", "profile"],
        "Skills": ["skills", "technical skills", "technologies"],
        "Experience": ["experience", "internship", "employment", "work experience"],
        "Projects": ["projects", "project experience"],
        "Education": ["education", "academic", "qualification"],
    }

    section_results = {
        section: any(alias in lower_text for alias in aliases)
        for section, aliases in section_aliases.items()
    }

    contact_checks = {
        "Email": bool(re.search(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", text)),
        "Phone": bool(re.search(r"(?:\+?\d[\d\s().-]{8,}\d)", text)),
        "LinkedIn": "linkedin.com" in lower_text,
        "GitHub": "github.com" in lower_text,
    }

    required_keywords = list(dict.fromkeys(jd_skills or []))
    matched_keywords = [s for s in required_keywords if s.lower() in lower_text]
    missing_keywords = [s for s in required_keywords if s.lower() not in lower_text]

    keyword_coverage = (
        len(matched_keywords) / len(required_keywords) * 100
        if required_keywords else 100.0
    )

    quantified_patterns = [
        r"\b\d+%\b",
        r"\b\d+[+]?\s*(?:users|customers|records|requests|projects|apis|tests)\b",
        r"\b(?:increased|decreased|improved|reduced|achieved|saved)\b.{0,50}\b\d+",
    ]
    quantified_count = sum(
        len(re.findall(pattern, lower_text))
        for pattern in quantified_patterns
    )
    has_quantified_results = quantified_count > 0

    action_verbs = [
        "developed", "built", "implemented", "designed", "created",
        "automated", "optimized", "deployed", "integrated", "tested",
        "analyzed", "improved", "develop", "build", "implement",
    ]
    action_verb_count = sum(
        len(re.findall(r"\b" + re.escape(v) + r"\b", lower_text))
        for v in action_verbs
    )

    section_score = sum(section_results.values()) / len(section_results) * 100
    contact_score = sum(contact_checks.values()) / len(contact_checks) * 100
    quantification_score = 100.0 if has_quantified_results else 40.0
    action_score = min(action_verb_count / 3, 1.0) * 100

    ats_score = (
        keyword_coverage * 0.40
        + section_score * 0.25
        + contact_score * 0.15
        + quantification_score * 0.10
        + action_score * 0.10
    )

    if ats_score >= 80:
        ats_status = "Strong ATS readiness"
    elif ats_score >= 60:
        ats_status = "Good ATS readiness"
    elif ats_score >= 40:
        ats_status = "Moderate ATS readiness"
    else:
        ats_status = "Needs ATS improvement"

    improvements = []
    missing_sections = [
        name for name, found in section_results.items() if not found
    ]
    if missing_sections:
        improvements.append(
            "Add clear standard sections: "
            + ", ".join(missing_sections[:3]) + "."
        )
    if missing_keywords:
        improvements.append(
            "Add relevant job keywords only where they accurately reflect "
            "your experience: " + ", ".join(missing_keywords[:5]) + "."
        )
    if not has_quantified_results:
        improvements.append(
            "Add measurable results to projects or experience, such as "
            "percentages, time saved, users served, or accuracy improvements."
        )
    if contact_score < 100:
        improvements.append(
            "Make sure your email, phone, LinkedIn, and GitHub are clearly "
            "visible if applicable."
        )
    if action_verb_count < 3:
        improvements.append(
            "Use strong action verbs such as built, implemented, automated, "
            "optimized, and deployed in project bullets."
        )

    return {
        "score": float(ats_score),
        "status": ats_status,
        "sections": section_results,
        "contact": contact_checks,
        "matched_keywords": matched_keywords,
        "missing_keywords": missing_keywords,
        "keyword_coverage": float(keyword_coverage),
        "has_quantified_results": has_quantified_results,
        "action_verb_count": action_verb_count,
        "improvements": improvements[:6],
    }


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Resume Job Match Analyzer",
    page_icon="📄",
    layout="wide",
    initial_sidebar_state="collapsed"
)


# ============================================================
# CSS
# ============================================================

st.markdown(
    """
    <style>

    .main {
        padding-top: 2rem;
    }

    .main-title {
        font-size: 42px;
        font-weight: 700;
        margin-bottom: 5px;
    }

    .subtitle {
        font-size: 18px;
        opacity: 0.75;
        margin-bottom: 30px;
    }

    .skill-tag {
        display: inline-block;
        padding: 7px 12px;
        margin: 4px;
        border-radius: 20px;
        border: 1px solid rgba(128, 128, 128, 0.35);
        background-color: rgba(128, 128, 128, 0.10);
        color: inherit;
        font-size: 14px;
    }

    .recommendation {
        padding: 16px 18px;
        margin: 10px 0;
        border-radius: 10px;
        border: 1px solid rgba(128, 128, 128, 0.35);
        background-color: rgba(128, 128, 128, 0.10);
        color: inherit;
        font-size: 16px;
    }

    .evidence-box {
        padding: 14px 18px;
        margin: 8px 0;
        border-radius: 10px;
        border-left: 4px solid #4CAF50;
        background-color: rgba(76, 175, 80, 0.08);
        color: inherit;
    }

    .missing-evidence {
        padding: 14px 18px;
        margin: 8px 0;
        border-radius: 10px;
        border-left: 4px solid #F44336;
        background-color: rgba(244, 67, 54, 0.08);
        color: inherit;
    }

    .footer {
        text-align: center;
        opacity: 0.65;
        margin-top: 50px;
        padding: 20px;
        font-size: 14px;
    }

    </style>
    """,
    unsafe_allow_html=True
)


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="main-title">📄 Resume → Job Match Analyzer</div>',
    unsafe_allow_html=True
)

st.markdown(
    """
    <div class="subtitle">
        Analyze how well your resume matches a job description
        using NLP, semantic similarity, and skill analysis.
    </div>
    """,
    unsafe_allow_html=True
)


# ============================================================
# INPUT
# ============================================================

input_col1, input_col2 = st.columns(
    [1, 1],
    gap="large"
)


# ============================================================
# RESUME UPLOAD
# ============================================================

with input_col1:

    st.subheader(
        "📄 Your Resume"
    )

    resume_file = st.file_uploader(
        "Upload your resume PDF",
        type=["pdf"],
        label_visibility="collapsed"
    )

    if resume_file:

        st.success(
            f"Uploaded: {resume_file.name}"
        )


# ============================================================
# JOB DESCRIPTION
# ============================================================

with input_col2:

    st.subheader(
        "💼 Job Description"
    )

    job_description = st.text_area(
        "Paste job description",
        height=200,
        placeholder=(
            "Paste the complete job description here..."
        ),
        label_visibility="collapsed"
    )


st.write("")


# ============================================================
# ANALYZE
# ============================================================

analyze = st.button(
    "🔍 Analyze Resume",
    use_container_width=True
)


if analyze:

    # ========================================================
    # VALIDATION
    # ========================================================

    if resume_file is None:

        st.error(
            "Please upload your resume PDF."
        )

        st.stop()


    if not job_description.strip():

        st.error(
            "Please paste the job description."
        )

        st.stop()


    try:

        # ====================================================
        # PDF EXTRACTION
        # ====================================================

        with st.spinner(
            "Reading your resume..."
        ):

            resume_text = (
                extract_text_from_pdf(
                    resume_file
                )
            )


        if not resume_text.strip():

            st.error(
                "Could not extract text from the PDF. "
                "Please upload a text-based PDF."
            )

            st.stop()


        # ====================================================
        # SEMANTIC SIMILARITY
        # ====================================================

        with st.spinner(
            "Analyzing resume and job description..."
        ):

            semantic_score = (
                calculate_similarity(
                    resume_text,
                    job_description
                )
            )


        # ====================================================
        # SKILL EXTRACTION
        # ====================================================

        resume_skills = normalize_skills(
            extract_skills(
                resume_text
            )
        )

        jd_skills = normalize_skills(
            extract_skills(
                job_description
            )
        )

        # ====================================================
        # ATS ANALYSIS
        # ====================================================

        ats_result = analyze_ats(
            resume_text,
            job_description,
            jd_skills
        )


        # ====================================================
        # SKILL MATCHING
        # ====================================================

        matched_skills = sorted(
            set(resume_skills)
            & set(jd_skills)
        )

        missing_skills = sorted(
            set(jd_skills)
            - set(resume_skills)
        )


        # ====================================================
        # EXPERIENCE
        # ====================================================

        experience_match = (
            calculate_experience_match(
                resume_text,
                job_description
            )
        )


        # ====================================================
        # SKILL COVERAGE
        # ====================================================

        if jd_skills:

            skill_percentage = (
                len(matched_skills)
                / len(jd_skills)
            ) * 100

        else:

            skill_percentage = 100.0


        # ====================================================
        # EXPERIENCE SCORE
        # ====================================================

        if experience_match == "Good":

            experience_score = 100

        elif experience_match == "Moderate":

            experience_score = 60

        else:

            experience_score = 30


        # ====================================================
        # FINAL SCORE
        # ====================================================

        final_score = calculate_final_score(
            semantic_score,
            matched_skills,
            jd_skills,
            experience_match
        )


        # ====================================================
        # ATS ANALYSIS
        # ====================================================

        st.divider()
        st.header("🤖 ATS Compatibility Analysis")

        ats_col1, ats_col2, ats_col3 = st.columns(3)

        with ats_col1:
            st.metric("ATS Compatibility", f"{ats_result['score']:.1f}%")

        with ats_col2:
            st.metric(
                "Job Keywords Covered",
                f"{ats_result['keyword_coverage']:.1f}%"
            )

        with ats_col3:
            st.metric(
                "Resume Sections",
                f"{sum(ats_result['sections'].values())}/{len(ats_result['sections'])}"
            )

        st.progress(
            min(max(float(ats_result["score"]) / 100, 0.0), 1.0)
        )

        if ats_result["score"] >= 80:
            st.success("🟢 " + ats_result["status"])
        elif ats_result["score"] >= 60:
            st.info("🟡 " + ats_result["status"])
        else:
            st.warning("🟠 " + ats_result["status"])

        ats_detail_col1, ats_detail_col2 = st.columns(2, gap="large")

        with ats_detail_col1:
            st.subheader("📑 Resume Structure")
            for section, found in ats_result["sections"].items():
                st.write(("✓ " if found else "✗ ") + section)

        with ats_detail_col2:
            st.subheader("📇 Contact Information")
            for item, found in ats_result["contact"].items():
                st.write(("✓ " if found else "✗ ") + item)

        st.subheader("🔑 Job-Specific Keywords")

        if ats_result["matched_keywords"]:
            st.write(
                "**Covered:** "
                + ", ".join(ats_result["matched_keywords"])
            )
        else:
            st.write("No detected job-specific keywords are currently covered.")

        if ats_result["missing_keywords"]:
            st.write(
                "**Missing:** "
                + ", ".join(ats_result["missing_keywords"])
            )

        st.caption(
            "ATS score is a project-specific heuristic, not a score from a real "
            "company's ATS. Keywords should only be added when they truthfully "
            "represent your experience."
        )

        if ats_result["improvements"]:
            st.subheader("💡 ATS Improvements")
            for index, item in enumerate(
                ats_result["improvements"],
                start=1
            ):
                st.markdown(
                    f"<div class=\"recommendation\"><strong>{index}.</strong> {item}</div>",
                    unsafe_allow_html=True
                )


        # ====================================================
        # RECOMMENDATIONS
        # ====================================================

        recommendations = (
            generate_recommendations(
                missing_skills
            )
        )


        # ====================================================
        # EVIDENCE
        # ====================================================

        evidence = extract_skill_evidence(
            resume_text,
            matched_skills
        )


        # ====================================================
        # RESULTS
        # ====================================================

        st.divider()

        st.header(
            "🎯 Resume Match Result"
        )


        # ====================================================
        # SCORE CARDS
        # ====================================================

        score_col1, score_col2, score_col3 = (
            st.columns(3)
        )


        with score_col1:

            st.metric(
                "Final Match Score",
                f"{final_score}%"
            )


        with score_col2:

            st.metric(
                "Semantic Similarity",
                f"{semantic_score}%"
            )


        with score_col3:

            st.metric(
                "Skill Coverage",
                f"{skill_percentage:.1f}%"
            )


        # ====================================================
        # SCORE BAR
        # ====================================================

        st.progress(
            min(
                max(
                    float(final_score) / 100,
                    0.0
                ),
                1.0
            )
        )


        # ====================================================
        # SCORE MESSAGE
        # ====================================================

        if final_score >= 80:

            st.success(
                "🔥 Strong match! Your resume aligns well "
                "with this job."
            )

        elif final_score >= 60:

            st.info(
                "👍 Good match, but there are some areas "
                "you can improve."
            )

        elif final_score >= 40:

            st.warning(
                "⚠️ Moderate match. Consider improving "
                "your resume for this role."
            )

        else:

            st.error(
                "❗ Low match. This resume may need "
                "significant changes for this role."
            )


        # ====================================================
        # SCORE BREAKDOWN
        # ====================================================

        st.subheader(
            "📊 Score Breakdown"
        )


        breakdown_col1, breakdown_col2, breakdown_col3 = (
            st.columns(3)
        )


        with breakdown_col1:

            st.metric(
                "Semantic Similarity",
                f"{semantic_score}%"
            )

            st.caption(
                "60% of final score"
            )


        with breakdown_col2:

            st.metric(
                "Skill Coverage",
                f"{skill_percentage:.1f}%"
            )

            st.caption(
                "30% of final score"
            )


        with breakdown_col3:

            st.metric(
                "Experience",
                f"{experience_score}%"
            )

            st.caption(
                "10% of final score"
            )


        # ====================================================
        # EXPERIENCE MATCH
        # ====================================================

        st.divider()

        st.header(
            "💼 Experience Match"
        )


        if experience_match == "Good":

            st.success(
                "🟢 Good — Your experience appears "
                "relevant to this role."
            )

        elif experience_match == "Moderate":

            st.warning(
                "🟡 Moderate — Your experience partially "
                "matches the role."
            )

        else:

            st.error(
                "🔴 Low — The job may require more "
                "experience than shown in your resume."
            )


        # ====================================================
        # SKILL ANALYSIS
        # ====================================================

        st.divider()

        st.header(
            "🛠️ Skill Analysis"
        )


        skill_col1, skill_col2 = st.columns(
            2,
            gap="large"
        )


        # ====================================================
        # MATCHED
        # ====================================================

        with skill_col1:

            st.subheader(
                "✅ Matched Skills"
            )


            if matched_skills:

                for skill in matched_skills:

                    st.markdown(
                        f"""
                        <span class="skill-tag">
                            ✓ {skill}
                        </span>
                        """,
                        unsafe_allow_html=True
                    )

            else:

                st.info(
                    "No matching skills were detected."
                )


        # ====================================================
        # MISSING
        # ====================================================

        with skill_col2:

            st.subheader(
                "❌ Missing Skills"
            )


            if missing_skills:

                for skill in missing_skills:

                    st.markdown(
                        f"""
                        <span class="skill-tag">
                            ✗ {skill}
                        </span>
                        """,
                        unsafe_allow_html=True
                    )

            else:

                st.success(
                    "🎉 No major missing skills detected!"
                )


        # ====================================================
        # EVIDENCE MATCHING
        # ====================================================

        st.divider()

        st.header(
            "🔎 Skill Evidence"
        )

        st.caption(
            "Evidence shows where a matched skill "
            "was found in your resume."
        )


        # ----------------------------------------------------
        # MATCHED SKILL EVIDENCE
        # ----------------------------------------------------

        if matched_skills:

            for skill in matched_skills:

                skill_evidence = evidence.get(
                    skill
                )


                if skill_evidence:

                    st.markdown(
                        f"""
                        <div class="evidence-box">
                            <strong>✅ {skill}</strong>
                            <br><br>
                            <strong>Resume evidence:</strong>
                            <br>
                            "{skill_evidence}"
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

                else:

                    st.markdown(
                        f"""
                        <div class="missing-evidence">
                            <strong>⚠️ {skill}</strong>
                            <br><br>
                            Skill detected, but a specific
                            evidence sentence could not
                            be extracted.
                        </div>
                        """,
                        unsafe_allow_html=True
                    )


        else:

            st.info(
                "No matched skills are available "
                "for evidence analysis."
            )


        # ====================================================
        # MISSING SKILL EVIDENCE
        # ====================================================

        if missing_skills:

            st.subheader(
                "❌ Missing Skill Evidence"
            )

            st.caption(
                "These requirements were detected in the "
                "job description but no matching skill "
                "was detected in your resume."
            )


            for skill in missing_skills:

                st.markdown(
                    f"""
                    <div class="missing-evidence">
                        <strong>✗ {skill}</strong>
                        <br>
                        No evidence found in resume.
                    </div>
                    """,
                    unsafe_allow_html=True
                )


        # ====================================================
        # SKILL COVERAGE
        # ====================================================

        st.divider()

        st.subheader(
            "📈 Required Skill Coverage"
        )


        st.progress(
            min(
                max(
                    float(skill_percentage) / 100,
                    0.0
                ),
                1.0
            )
        )


        st.write(
            f"**{skill_percentage:.1f}%** of detected "
            "job requirements are covered by your resume."
        )


        # ====================================================
        # RECOMMENDATIONS
        # ====================================================

        st.divider()

        st.header(
            "💡 Suggested Improvements"
        )


        if recommendations:

            for index, recommendation in enumerate(
                recommendations,
                start=1
            ):

                st.markdown(
                    f"""
                    <div class="recommendation">
                        <strong>{index}.</strong>
                        {recommendation}
                    </div>
                    """,
                    unsafe_allow_html=True
                )

        else:

            st.success(
                "Your resume already covers the major "
                "requirements of this job."
            )


        # ====================================================
        # SUMMARY
        # ====================================================

        st.divider()

        st.header(
            "📋 Analysis Summary"
        )


        summary_col1, summary_col2, summary_col3 = (
            st.columns(3)
        )


        with summary_col1:

            st.metric(
                "Final Score",
                f"{final_score}%"
            )


        with summary_col2:

            st.metric(
                "Matched Skills",
                len(matched_skills)
            )


        with summary_col3:

            st.metric(
                "Missing Skills",
                len(missing_skills)
            )


        # ====================================================
        # DOWNLOAD PDF REPORT
        # ====================================================

        st.divider()

        st.header("📥 Download Analysis Report")

        pdf_report = create_pdf_report(
            final_score=final_score,
            semantic_score=semantic_score,
            skill_percentage=skill_percentage,
            experience_match=experience_match,
            matched_skills=matched_skills,
            missing_skills=missing_skills,
            recommendations=recommendations,
            evidence=evidence,
            ats_result=ats_result,
        )

        st.download_button(
            label="📄 Download PDF Report",
            data=pdf_report,
            file_name="resume_job_match_report.pdf",
            mime="application/pdf",
            use_container_width=True,
        )


        # ====================================================
        # FOOTER
        # ====================================================

        st.markdown(
            """
            <div class="footer">
                Built with Python · Sentence Transformers ·
                Scikit-learn · PyMuPDF · Streamlit
            </div>
            """,
            unsafe_allow_html=True
        )


    # ========================================================
    # ERROR HANDLING
    # ========================================================

    except Exception as e:

        st.error(
            "Something went wrong while analyzing "
            "the resume."
        )

        st.exception(e)